---
name: Test Documentation

# Triggers the workflow on push or pull request events
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Test documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: lint markdown files
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: .

      - name: lint yaml files
        uses: ibiqlik/action-yamllint@v2
